import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  header: {
    position: "absolute",
    top: 50,
    left: 20,
    right: 20,
    zIndex: 10,
    flexDirection: "row",
    backgroundColor: "rgba(0,0,0,0.85)",
    padding: 15,
    borderRadius: 15,
    alignItems: "center",
  },
  headerLabel: { color: "#aaa", fontSize: 10, textTransform: "uppercase" },
  headerValue: { color: "#fff", fontSize: 18, fontWeight: "bold" },
  headerSubtext: { color: "#888", fontSize: 12 },
  allergenChip: {
    backgroundColor: "#ef4444",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    marginRight: 6,
  },
  allergenChipText: { color: "#fff", fontSize: 11, fontWeight: "600" },
  switchButton: {
    backgroundColor: "#2f95dc",
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 10,
  },
  buttonText: { color: "#fff", fontWeight: "bold" },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  },
  profileBox: {
    backgroundColor: "white",
    padding: 25,
    borderRadius: 20,
    width: "80%",
  },
  profileTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
  },
  profileItem: { padding: 15, borderBottomWidth: 1, borderColor: "#eee" },
  profileItemActive: { backgroundColor: "#f0f9ff" },
  profileText: { fontSize: 16, textAlign: "center" },
  profileTextActive: { color: "#2f95dc", fontWeight: "bold" },
  cancel: { marginTop: 10, alignItems: "center" },
  fullLoading: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 999,
  },
  scannerOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  scannerBox: {
    width: 250,
    height: 250,
    backgroundColor: "transparent",
    position: "relative",
  },
  scanText: {
    color: "white",
    fontSize: 16,
    marginTop: 30,
    fontWeight: "600",
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
  },
  corner: {
    position: "absolute",
    width: 40,
    height: 40,
    borderColor: "#10B981",
    borderWidth: 5,
  },
  cornerTL: {
    top: 0,
    left: 0,
    borderBottomWidth: 0,
    borderRightWidth: 0,
    borderTopLeftRadius: 20,
  },
  cornerTR: {
    top: 0,
    right: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderTopRightRadius: 20,
  },
  cornerBL: {
    bottom: 0,
    left: 0,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomLeftRadius: 20,
  },
  cornerBR: {
    bottom: 0,
    right: 0,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    borderBottomRightRadius: 20,
  },

  // ================= 扫码结果卡片相关样式 =================
  resultOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end", // 让弹窗靠下
    alignItems: "center",
    zIndex: 150,
  },
  resultCard: {
    backgroundColor: "white",
    width: "100%",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    padding: 25,
    paddingBottom: 120,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 10,
  },
  safeTitle: { fontSize: 22, fontWeight: "bold", color: "#16A34A", marginBottom: 10 },
  warningTitle: { fontSize: 22, fontWeight: "bold", color: "#DC2626", marginBottom: 10 },
  productImage: { width: 120, height: 120, marginBottom: 15, borderRadius: 10 },
  productName: { fontSize: 18, fontWeight: "bold", textAlign: "center", marginBottom: 5 },
  warningText: { fontSize: 16, color: "#DC2626", fontWeight: "600", marginBottom: 10 },
  safeText: { fontSize: 16, color: "#4B5563", marginBottom: 10 },
  
  // 展开详情相关
  toggleText: { color: "#3B82F6", fontWeight: "bold", fontSize: 14, marginVertical: 10, textAlign: "center" },
  detailsBox: { width: "100%", backgroundColor: "#F3F4F6", padding: 15, borderRadius: 10, marginBottom: 15 },
  ingredientsTitle: { fontWeight: "bold", marginBottom: 5, color: "#374151" },
  ingredientsText: { fontSize: 14, lineHeight: 20 },

  // 按钮相关
  actionRow: { flexDirection: "row", width: "100%", justifyContent: "space-between", marginTop: 10 },
  addButtonSafe: { backgroundColor: "#16A34A", padding: 15, borderRadius: 12, flex: 1, alignItems: "center" },
  addButtonUnsafe: { backgroundColor: "#D1D5DB", padding: 15, borderRadius: 12, flex: 1, alignItems: "center", marginLeft: 10 },
  findAltButton: { backgroundColor: "#F59E0B", padding: 15, borderRadius: 12, flex: 1, alignItems: "center" },
  
  cancelBtn: { marginTop: 15, padding: 10 },
  cancelBtnText: { color: "#6B7280", fontSize: 16, fontWeight: "600" },
});